// Generated by CoffeeScript 1.6.2
(function() {
  var gen_replacer, stringify;

  gen_replacer = function(num) {
    var mult;

    mult = Math.pow(10, num);
    return function(k, v) {
      var alt1, alt2;

      if ((v.toFixed != null) && (v !== parseInt(v))) {
        alt1 = parseFloat(v.toPrecision(num));
        if (("" + alt1).length < ("" + v).length) {
          alt2 = Math.round(v);
          if ((Math.abs(alt2 - v) < Math.abs(alt1 - v)) && ("" + alt2).length <= ("" + alt1).length) {
            alt1 = alt2;
          }
          return alt1;
        }
      }
      return v;
    };
  };

  exports.stringify = stringify = function(o, precision, spacer) {
    return JSON.stringify(o, gen_replacer(precision), spacer);
  };

}).call(this);
